(module
  (import "env" "throw_longjmp" (func $throw_longjmp))
  (import "env" "invoke_ii" (func $invoke_ii (param i32 i32) (result i32)))

  (memory (export "memory") 1)
  (table (export "__indirect_function_table") 5 funcref)
  (type $i_i (func (param i32) (result i32)))

  (global $threwBit (mut i32) (i32.const 0))
  (global $threwValue (mut i32) (i32.const 0))

  (func $setThrew (param $0 i32) (param $1 i32)
    (if (i32.eqz (global.get $threwBit))
      (then
        (global.set $threwValue (local.get $1))
        (global.set $threwBit (local.get $0))
      )
    )
  )

  (func $emscripten_longjmp (param $0 i32) (param $1 i32)
    (call $setThrew (local.get $0)
      (select (i32.const 1) (local.get $1) (i32.le_u (local.get $1) (i32.const 1)))
    )
    (call $throw_longjmp)
    (unreachable)
  )

  (func $identity (param i32) (result i32)
    local.get 0
  )

  (func $throwing_func (param i32) (result i32)
    (call $emscripten_longjmp (i32.const 1) (i32.const 1))
    (unreachable)
  )

  (func $nested_throw (param i32) (result i32)
    (call $invoke_ii (i32.const 2) (local.get 0))
  )

  (func $b (param i32) (result i32)
    (if (result i32) (i32.gt_s (local.get 0) (i32.const 0))
      (then
        (i32.mul (local.get 0) (i32.const 2))
      )
      (else
        (call $emscripten_longjmp (i32.const 1) (i32.const 0))
        (unreachable)
      )
    )
  )

  (func $a (param i32) (result i32)
    (local $result i32)
    (global.set $threwBit (i32.const 0))
    (global.set $threwValue (i32.const 0))
    (local.set $result (call $invoke_ii (i32.const 4) (local.get 0)))
    (if (result i32) (global.get $threwBit)
      (then (i32.const -1))
      (else (local.get $result))
    )
  )

  (func $setjmp_test (param $env i32) (result i32)
    (local $result i32)
    (global.set $threwBit (i32.const 0))
    (global.set $threwValue (i32.const 0))
    (local.set $result (call $invoke_ii (i32.const 2) (i32.const 0)))
    (if (result i32) (global.get $threwBit)
      (then
        (i32.const -1)
      )
      (else
        (local.get $result)
      )
    )
  )

  (func $test_no_throw (result i32)
    (local $result i32)
    (global.set $threwBit (i32.const 0))
    (global.set $threwValue (i32.const 0))
    (local.set $result (call $invoke_ii (i32.const 0) (i32.const 10)))
    (if (result i32) (global.get $threwBit)
      (then (i32.const -1))
      (else (local.get $result))
    )
  )

  (func $test_throw (result i32)
    (local $result i32)
    (global.set $threwBit (i32.const 0))
    (global.set $threwValue (i32.const 0))
    (local.set $result (call $invoke_ii (i32.const 1) (i32.const 0)))
    (if (result i32) (global.get $threwBit)
      (then (global.get $threwBit))
      (else (local.get $result))
    )
  )

  (func $test_nested_invoke (result i32)
    (local $result i32)
    (global.set $threwBit (i32.const 0))
    (global.set $threwValue (i32.const 0))
    (local.set $result (call $invoke_ii (i32.const 3) (i32.const 0)))
    (if (result i32) (global.get $threwBit)
      (then (global.get $threwBit))
      (else (local.get $result))
    )
  )

  (elem (i32.const 0) $identity $throwing_func $throwing_func $nested_throw $b)

  (export "identity" (func $identity))
  (export "a" (func $a))
  (export "test_no_throw" (func $test_no_throw))
  (export "test_throw" (func $test_throw))
  (export "test_nested_invoke" (func $test_nested_invoke))
  (export "setjmp_test" (func $setjmp_test))
  (export "setThrew" (func $setThrew))
)
