// Auto-generated by tools/gen_enum_map.sh from quickwin_const.d.ts. DO NOT EDIT.
// Regenerate with: make enum-map   (run after regenerating quickwin_const.d.ts)
//
// EnumMap — token 枚举标注 ('u32@Name' / '<>ptr@Name') 的值域表：全局
// interface 声明合并（详见 lib/ffi/ctype.ts），用户可在自己的 .d.ts 里直接扩展。
// 重名枚举取跨模块值域并集。
interface EnumMap {
    GetWindowCmd: import('gui').GetWindowCmd
    SetWindowPosFlag: import('gui').SetWindowPosFlag
    SetWindowPosHwnd: import('gui').SetWindowPosHwnd
    NotifyIconCmd: import('gui').NotifyIconCmd
    NotifyIconFlag: import('gui').NotifyIconFlag
    MenuFlag: import('gui').MenuFlag
    WindowStyle: import('gui').WindowStyle
    WmMsg: import('gui').WmMsg
    ScrollBar: import('gui').ScrollBar
    ScrollCmd: import('gui').ScrollCmd
    ScrollInfoFlag: import('gui').ScrollInfoFlag
    SysMetrics: import('gui').SysMetrics
    ButtonStyle: import('gui').ButtonStyle
    MouseKeyFlag: import('gui').MouseKeyFlag
    LbMsg: import('gui').LbMsg
    StaticStyle: import('gui').StaticStyle
    EditStyle: import('gui').EditStyle
    ComboBoxStyle: import('gui').ComboBoxStyle
    ListBoxStyle: import('gui').ListBoxStyle
    LbnCode: import('gui').LbnCode
    TabStyle: import('gui').TabStyle
    TcMsg: import('gui').TcMsg
    TcNotifyCode: import('gui').TcNotifyCode
    TcItemFlag: import('gui').TcItemFlag
    ListViewStyle: import('gui').ListViewStyle
    LvExStyle: import('gui').LvExStyle
    LvMsg: import('gui').LvMsg
    LvImageList: import('gui').LvImageList
    ImageListFlag: import('gui').ImageListFlag
    HitTest: import('gui').HitTest
    StandardCursor: import('gui').StandardCursor
    LvItemFlag: import('gui').LvItemFlag
    LvItemState: import('gui').LvItemState
    LvColumnMask: import('gui').LvColumnMask
    LvColumnFormat: import('gui').LvColumnFormat
    FontWeight: import('gui').FontWeight
    LvNavFlag: import('gui').LvNavFlag
    LvColumnWidthCmd: import('gui').LvColumnWidthCmd
    HdmMsg: import('gui').HdmMsg
    LvNotifyCode: import('gui').LvNotifyCode
    CustomDrawStage: import('gui').CustomDrawStage
    CustomDrawFlag: import('gui').CustomDrawFlag
    ShowWindowCmd: import('gui').ShowWindowCmd
    ButtonMsg: import('gui').ButtonMsg
    ButtonCheckState: import('gui').ButtonCheckState
    ButtonExtMsg: import('gui').ButtonExtMsg
    EditMsg: import('gui').EditMsg
    EditNotify: import('gui').EditNotify
    ComboBoxMsg: import('gui').ComboBoxMsg
    CbnCode: import('gui').CbnCode
    ProgressMsg: import('gui').ProgressMsg
    ProgressStyle: import('gui').ProgressStyle
    TrackBarStyle: import('gui').TrackBarStyle
    TbMsg: import('gui').TbMsg
    DtStyle: import('gui').DtStyle
    DtMsg: import('gui').DtMsg
    DtNotifyCode: import('gui').DtNotifyCode
    DtFlag: import('gui').DtFlag
    TreeViewStyle: import('gui').TreeViewStyle
    TvInsertAfter: import('gui').TvInsertAfter
    TvMsg: import('gui').TvMsg
    TvExStyle: import('gui').TvExStyle
    TvNotifyCode: import('gui').TvNotifyCode
    TvExpandCmd: import('gui').TvExpandCmd
    TvIfFlag: import('gui').TvIfFlag
    TvGnRelative: import('gui').TvGnRelative
    Gwlp: import('gui').Gwlp
    SysLinkMsg: import('gui').SysLinkMsg
    SysLinkNotifyCode: import('gui').SysLinkNotifyCode
    LinkStyle: import('gui').LinkStyle
    TtMsg: import('gui').TtMsg
    TooltipStyle: import('gui').TooltipStyle
    CreatePos: import('gui').CreatePos
    TtToolFlag: import('gui').TtToolFlag
    RasterOp: import('gui').RasterOp
    OpenFileNameFlag: import('gui').OpenFileNameFlag
    HKey: import('gui').HKey
    RegAccess: import('gui').RegAccess
    RegType: import('gui').RegType
    PrinterEnum: import('gui').PrinterEnum
    DeviceCap: import('gui').DeviceCap
    StaticMsg: import('gui').StaticMsg
    StaticStyleEx: import('gui').StaticStyleEx
    ImageType: import('gui').ImageType
    LoadImageFlag: import('gui').LoadImageFlag
    IDI: import('gui').IDI
    DrawTextFlag: import('gui').DrawTextFlag
    ProcessCreationFlag: import('gui').ProcessCreationFlag
    ErrorCode: import('gui').ErrorCode | import('wolfssl').ErrorCode
    PowerBroadcast: import('gui').PowerBroadcast
    DevMode: import('gui').DevMode
    Guid: import('gui').Guid
    AddrFamily: import('sock').AddrFamily
    SockType: import('sock').SockType
    Protocol: import('sock').Protocol
    Shutdown: import('sock').Shutdown
    FdEvent: import('sock').FdEvent
    VerifyMode: import('wolfssl').VerifyMode
    SniType: import('wolfssl').SniType
    FileType: import('wolfssl').FileType
    ReturnCode: import('wolfssl').ReturnCode

    // 聚合消息枚举（脚本按 *Msg 后缀自动收集）：SendMessage/DefWindowProc 的
    // msg 位值域 = 窗口消息 ∪ 各控件消息；标志位组合、通知码不在此域。
    AnyMsg: import('gui').WmMsg | import('gui').LbMsg | import('gui').TcMsg | import('gui').LvMsg | import('gui').HdmMsg | import('gui').ButtonMsg | import('gui').ButtonExtMsg | import('gui').EditMsg | import('gui').ComboBoxMsg | import('gui').ProgressMsg | import('gui').TbMsg | import('gui').DtMsg | import('gui').TvMsg | import('gui').SysLinkMsg | import('gui').TtMsg | import('gui').StaticMsg
}
