// Auto-generated by tools/gen_const.c. DO NOT EDIT.
// Regenerate with: make const

declare module "gui" {

    export const enum GetWindowCmd {
        FIRST = 0, // 0x0
        LAST = 1, // 0x1
        NEXT = 2, // 0x2
        PREV = 3, // 0x3
        OWNER = 4, // 0x4
        CHILD = 5, // 0x5
    }

    export const enum SetWindowPosFlag {
        SWP_NOSIZE = 1, // 0x1
        SWP_NOMOVE = 2, // 0x2
        SWP_NOZORDER = 4, // 0x4
        SWP_NOACTIVATE = 16, // 0x10
        SWP_SHOWWINDOW = 64, // 0x40
        SWP_HIDEWINDOW = 128, // 0x80
        SWP_FRAMECHANGED = 32, // 0x20
    }

    export const enum SetWindowPosHwnd {
        TOP = 0, // 0x0
        TOPMOST = -1, // 0xFFFFFFFF
        NOTOPMOST = -2, // 0xFFFFFFFE
    }

    export const enum NotifyIconCmd {
        ADD = 0, // 0x0
        MODIFY = 1, // 0x1
        DELETE = 2, // 0x2
    }

    export const enum NotifyIconFlag {
        MESSAGE = 1, // 0x1
        ICON = 2, // 0x2
        TIP = 4, // 0x4
    }

    export const enum MenuFlag {
        STRING = 0, // 0x0
        SEPARATOR = 2048, // 0x800
        CHECKED = 8, // 0x8
        GRAYED = 1, // 0x1
        DISABLED = 2, // 0x2
        POPUP = 16, // 0x10
    }

    export const enum WindowStyle {
        OVERLAPPEDWINDOW = 13565952, // 0xCF0000
        CHILD = 1073741824, // 0x40000000
        POPUP = -2147483648, // 0x80000000
        VISIBLE = 268435456, // 0x10000000
        BORDER = 8388608, // 0x800000
        HSCROLL = 1048576, // 0x100000
        VSCROLL = 2097152, // 0x200000
        CLIPCHILDREN = 33554432, // 0x2000000
        TABSTOP = 65536, // 0x10000
        GROUP = 131072, // 0x20000
    }

    export const enum WmMsg {
        NULL = 0, // 0x0
        CREATE = 1, // 0x1
        DESTROY = 2, // 0x2
        MOVE = 3, // 0x3
        SIZE = 5, // 0x5
        ACTIVATE = 6, // 0x6
        SETFOCUS = 7, // 0x7
        KILLFOCUS = 8, // 0x8
        ENABLE = 10, // 0xA
        SETREDRAW = 11, // 0xB
        SETTEXT = 12, // 0xC
        GETTEXT = 13, // 0xD
        GETTEXTLENGTH = 14, // 0xE
        PAINT = 15, // 0xF
        CLOSE = 16, // 0x10
        QUERYENDSESSION = 17, // 0x11
        QUIT = 18, // 0x12
        WINDOWPOSCHANGING = 70, // 0x46
        WINDOWPOSCHANGED = 71, // 0x47
        SYSCOMMAND = 274, // 0x112
        TIMER = 275, // 0x113
        HSCROLL = 276, // 0x114
        VSCROLL = 277, // 0x115
        INITMENU = 278, // 0x116
        INITMENUPOPUP = 279, // 0x117
        MOUSEWHEEL = 522, // 0x20A
        MOUSEMOVE = 512, // 0x200
        LBUTTONDOWN = 513, // 0x201
        LBUTTONUP = 514, // 0x202
        LBUTTONDBLCLK = 515, // 0x203
        RBUTTONDOWN = 516, // 0x204
        RBUTTONUP = 517, // 0x205
        RBUTTONDBLCLK = 518, // 0x206
        MBUTTONDOWN = 519, // 0x207
        MBUTTONUP = 520, // 0x208
        MBUTTONDBLCLK = 521, // 0x209
        MOUSEHOVER = 673, // 0x2A1
        MOUSELEAVE = 675, // 0x2A3
        KEYDOWN = 256, // 0x100
        KEYUP = 257, // 0x101
        CHAR = 258, // 0x102
        DEADCHAR = 259, // 0x103
        SYSKEYDOWN = 260, // 0x104
        SYSKEYUP = 261, // 0x105
        SYSCHAR = 262, // 0x106
        SYSDEADCHAR = 263, // 0x107
        UNICHAR = 265, // 0x109
        COMMAND = 273, // 0x111
        MENUSELECT = 287, // 0x11F
        MENUCHAR = 288, // 0x120
        ENTERIDLE = 289, // 0x121
        MENURBUTTONUP = 290, // 0x122
        MENUCOMMAND = 294, // 0x126
        UNINITMENUPOPUP = 293, // 0x125
        ENTERMENULOOP = 529, // 0x211
        EXITMENULOOP = 530, // 0x212
        SETFONT = 48, // 0x30
        GETFONT = 49, // 0x31
        SETHOTKEY = 50, // 0x32
        GETHOTKEY = 51, // 0x33
        DRAWITEM = 43, // 0x2B
        MEASUREITEM = 44, // 0x2C
        DELETEITEM = 45, // 0x2D
        COMPAREITEM = 57, // 0x39
        NCCREATE = 129, // 0x81
        NCDESTROY = 130, // 0x82
        NCCALCSIZE = 131, // 0x83
        NCHITTEST = 132, // 0x84
        NCPAINT = 133, // 0x85
        NCACTIVATE = 134, // 0x86
        NCMOUSEMOVE = 160, // 0xA0
        NCLBUTTONDOWN = 161, // 0xA1
        NCLBUTTONUP = 162, // 0xA2
        NCLBUTTONDBLCLK = 163, // 0xA3
        NCRBUTTONDOWN = 164, // 0xA4
        NCRBUTTONUP = 165, // 0xA5
        NCRBUTTONDBLCLK = 166, // 0xA6
        NCMBUTTONDOWN = 167, // 0xA7
        NCMBUTTONUP = 168, // 0xA8
        NCMBUTTONDBLCLK = 169, // 0xA9
        NCXBUTTONDOWN = 171, // 0xAB
        NCXBUTTONUP = 172, // 0xAC
        NCXBUTTONDBLCLK = 173, // 0xAD
        NCMOUSELEAVE = 674, // 0x2A2
        GETDLGCODE = 135, // 0x87
        SETCURSOR = 32, // 0x20
        MOUSEACTIVATE = 33, // 0x21
        CHILDACTIVATE = 34, // 0x22
        GETMINMAXINFO = 36, // 0x24
        DROPFILES = 563, // 0x233
        ENTERSIZEMOVE = 561, // 0x231
        EXITSIZEMOVE = 562, // 0x232
        SIZING = 532, // 0x214
        MOVING = 534, // 0x216
        CAPTURECHANGED = 533, // 0x215
        GETICON = 127, // 0x7F
        SETICON = 128, // 0x80
        ERASEBKGND = 20, // 0x14
        SYSCOLORCHANGE = 21, // 0x15
        HSCROLLCLIPBOARD = 782, // 0x30E
        VSCROLLCLIPBOARD = 778, // 0x30A
        QUERYUISTATE = 297, // 0x129
        CONTEXTMENU = 123, // 0x7B
        NOTIFY = 78, // 0x4E
        STYLECHANGING = 124, // 0x7C
        STYLECHANGED = 125, // 0x7D
        SHOWWINDOW = 24, // 0x18
        FONTCHANGE = 29, // 0x1D
        POWERBROADCAST = 536, // 0x218
        IME_STARTCOMPOSITION = 269, // 0x10D
        IME_ENDCOMPOSITION = 270, // 0x10E
        IME_COMPOSITION = 271, // 0x10F
        IME_SETCONTEXT = 641, // 0x281
        IME_NOTIFY = 642, // 0x282
        IME_CONTROL = 643, // 0x283
        IME_COMPOSITIONFULL = 644, // 0x284
        IME_SELECT = 645, // 0x285
        IME_CHAR = 646, // 0x286
        IME_REQUEST = 648, // 0x288
        IME_KEYDOWN = 656, // 0x290
        IME_KEYUP = 657, // 0x291
        TOUCH = 576, // 0x240
        DISPLAYCHANGE = 126, // 0x7E
        THEMECHANGED = 794, // 0x31A
        DWMCOLORIZATIONCOLORCHANGED = 800, // 0x320
        USER = 1024, // 0x400
    }

    export const enum ScrollBar {
        HORZ = 0, // 0x0
        VERT = 1, // 0x1
    }

    export const enum ScrollCmd {
        LINEUP = 0, // 0x0
        LINEDOWN = 1, // 0x1
        PAGEUP = 2, // 0x2
        PAGEDOWN = 3, // 0x3
        THUMBTRACK = 5, // 0x5
        THUMBPOSITION = 4, // 0x4
        TOP = 6, // 0x6
        BOTTOM = 7, // 0x7
        ENDSCROLL = 8, // 0x8
    }

    export const enum ScrollInfoFlag {
        RANGE = 1, // 0x1
        PAGE = 2, // 0x2
        POS = 4, // 0x4
        ALL = 23, // 0x17
    }

    export const enum SysMetrics {
        CXSCREEN = 0, // 0x0
        CYSCREEN = 1, // 0x1
    }

    export const enum ButtonStyle {
        PUSHBUTTON = 0, // 0x0
        DEFPUSHBUTTON = 1, // 0x1
        CHECKBOX = 2, // 0x2
        AUTOCHECKBOX = 3, // 0x3
        AUTORADIOBUTTON = 9, // 0x9
        GROUPBOX = 7, // 0x7
    }

    export const enum MouseKeyFlag {
        MK_SHIFT = 4, // 0x4
    }

    export const enum LbMsg {
        ADDSTRING = 384, // 0x180
        INSERTSTRING = 385, // 0x181
        DELETESTRING = 386, // 0x182
        RESETCONTENT = 388, // 0x184
        SETTOPINDEX = 407, // 0x197
        SETCURSEL = 390, // 0x186
        GETCURSEL = 392, // 0x188
        GETTEXT = 393, // 0x189
        GETTEXTLEN = 394, // 0x18A
        GETCOUNT = 395, // 0x18B
    }

    export const enum StaticStyle {
        LEFT = 0, // 0x0
    }

    export const enum EditStyle {
        LEFT = 0, // 0x0
        MULTILINE = 4, // 0x4
        PASSWORD = 32, // 0x20
        AUTOVSCROLL = 64, // 0x40
        AUTOHSCROLL = 128, // 0x80
        READONLY = 2048, // 0x800
        WANTRETURN = 4096, // 0x1000
        NUMBER = 8192, // 0x2000
    }

    export const enum ComboBoxStyle {
        DROPDOWNLIST = 3, // 0x3
        HASSTRINGS = 512, // 0x200
    }

    export const enum ListBoxStyle {
        NOTIFY = 1, // 0x1
        SORT = 2, // 0x2
        MULTIPLESEL = 8, // 0x8
        HASSTRINGS = 64, // 0x40
        NOINTEGRALHEIGHT = 256, // 0x100
        EXTENDEDSEL = 2048, // 0x800
        STANDARD = 10485763, // 0xA00003
    }

    export const enum LbnCode {
        SELCHANGE = 1, // 0x1
    }

    export const enum TabStyle {
        FOCUSNEVER = 32768, // 0x8000
        FIXEDWIDTH = 1024, // 0x400
    }

    export const enum TcMsg {
        GETITEMCOUNT = 4868, // 0x1304
        INSERTITEMW = 4926, // 0x133E
        DELETEITEM = 4872, // 0x1308
        DELETEALLITEMS = 4873, // 0x1309
        GETCURSEL = 4875, // 0x130B
        SETCURSEL = 4876, // 0x130C
    }

    export const enum TcNotifyCode {
        SELCHANGE = -551, // 0xFFFFFDD9
        SELCHANGING = -552, // 0xFFFFFDD8
    }

    export const enum TcItemFlag {
        TEXT = 1, // 0x1
    }

    export const enum ListViewStyle {
        REPORT = 1, // 0x1
        SINGLESEL = 4, // 0x4
        SHOWSELALWAYS = 8, // 0x8
        NOSORTHEADER = 32768, // 0x8000
    }

    export const enum LvExStyle {
        GRIDLINES = 1, // 0x1
        CHECKBOXES = 4, // 0x4
        TRACKSELECT = 8, // 0x8
        HEADERDRAGDROP = 16, // 0x10
        FULLROWSELECT = 32, // 0x20
        DOUBLEBUFFER = 65536, // 0x10000
    }

    export const enum LvMsg {
        GETITEMCOUNT = 4100, // 0x1004
        DELETEALLITEMS = 4105, // 0x1009
        GETNEXTITEM = 4108, // 0x100C
        GETITEMSTATE = 4140, // 0x102C
        SETITEMSTATE = 4139, // 0x102B
        GETSELECTEDCOUNT = 4146, // 0x1032
        SETEXTENDEDLISTVIEWSTYLE = 4150, // 0x1036
        INSERTCOLUMNW = 4193, // 0x1061
        GETSELECTIONMARK = 4162, // 0x1042
        INSERTITEMW = 4173, // 0x104D
        SETITEMW = 4172, // 0x104C
        ENSUREVISIBLE = 4115, // 0x1013
        SETCOLUMNWIDTH = 4126, // 0x101E
        DELETECOLUMN = 4124, // 0x101C
        GETHEADER = 4127, // 0x101F
        SUBITEMHITTEST = 4153, // 0x1039
        SETIMAGELIST = 4099, // 0x1003
    }

    export const enum LvImageList {
        NORMAL = 0, // 0x0
        SMALL = 1, // 0x1
        STATE = 2, // 0x2
    }

    export const enum ImageListFlag {
        MASK = 1, // 0x1
        COLOR = 0, // 0x0
        COLOR32 = 32, // 0x20
        HIGHQUALITYSCALE = 131072, // 0x20000
    }

    export const enum HitTest {
        CLIENT = 1, // 0x1
    }

    export const enum StandardCursor {
        ARROW = 32512, // 0x7F00
        IBEAM = 32513, // 0x7F01
        WAIT = 32514, // 0x7F02
        CROSS = 32515, // 0x7F03
        UPARROW = 32516, // 0x7F04
        SIZENWSE = 32642, // 0x7F82
        SIZENESW = 32643, // 0x7F83
        SIZEWE = 32644, // 0x7F84
        SIZENS = 32645, // 0x7F85
        SIZEALL = 32646, // 0x7F86
        NO = 32648, // 0x7F88
        HAND = 32649, // 0x7F89
        APPSTARTING = 32650, // 0x7F8A
        HELP = 32651, // 0x7F8B
    }

    export const enum LvItemFlag {
        TEXT = 1, // 0x1
        IMAGE = 2, // 0x2
        STATE = 8, // 0x8
    }

    export const enum LvItemState {
        FOCUSED = 1, // 0x1
        SELECTED = 2, // 0x2
    }

    export const enum LvColumnMask {
        FORMAT = 1, // 0x1
        WIDTH = 2, // 0x2
        TEXT = 4, // 0x4
    }

    export const enum LvColumnFormat {
        LEFT = 0, // 0x0
        CENTER = 2, // 0x2
        RIGHT = 1, // 0x1
    }

    export const enum FontWeight {
        NORMAL = 400, // 0x190
        BOLD = 700, // 0x2BC
    }

    export const enum LvNavFlag {
        SELECTED = 2, // 0x2
    }

    export const enum LvColumnWidthCmd {
        AUTOSIZE = -1, // 0xFFFFFFFF
        AUTOSIZE_USEHEADER = -2, // 0xFFFFFFFE
    }

    export const enum HdmMsg {
        GETITEMCOUNT = 4608, // 0x1200
    }

    export const enum LvNotifyCode {
        ITEMCHANGING = -100, // 0xFFFFFF9C
        ITEMCHANGED = -101, // 0xFFFFFF9B
        CLICK = -2, // 0xFFFFFFFE
        CUSTOMDRAW = -12, // 0xFFFFFFF4
    }

    export const enum CustomDrawStage {
        PREPAINT = 1, // 0x1
        ITEM = 65536, // 0x10000
        SUBITEM = 131072, // 0x20000
        ITEMPREPAINT = 65537, // 0x10001
        SUBITEMPREPAINT = 196609, // 0x30001
    }

    export const enum CustomDrawFlag {
        DODEFAULT = 0, // 0x0
        NEWFONT = 2, // 0x2
        NOTIFYITEMDRAW = 32, // 0x20
        NOTIFYSUBITEMDRAW = 32, // 0x20
    }

    export const enum ShowWindowCmd {
        HIDE = 0, // 0x0
        SHOWNORMAL = 1, // 0x1
        SHOWMINIMIZED = 2, // 0x2
        SHOWMAXIMIZED = 3, // 0x3
        SHOWNOACTIVATE = 4, // 0x4
        SHOW = 5, // 0x5
        MINIMIZE = 6, // 0x6
        SHOWMINNOACTIVE = 7, // 0x7
        SHOWNA = 8, // 0x8
        RESTORE = 9, // 0x9
        SHOWDEFAULT = 10, // 0xA
        FORCEMINIMIZE = 11, // 0xB
    }

    export const enum ButtonMsg {
        GETCHECK = 240, // 0xF0
        SETCHECK = 241, // 0xF1
    }

    export const enum ButtonCheckState {
        UNCHECKED = 0, // 0x0
        CHECKED = 1, // 0x1
    }

    export const enum ButtonExtMsg {
        GETIDEALSIZE = 5633, // 0x1601
    }

    export const enum EditMsg {
        GETSEL = 176, // 0xB0
        SETSEL = 177, // 0xB1
        SETCUEBANNER = 5377, // 0x1501
        SETPASSWORDCHAR = 204, // 0xCC
    }

    export const enum EditNotify {
        CHANGE = 768, // 0x300
    }

    export const enum ComboBoxMsg {
        ADDSTRING = 323, // 0x143
        SETCURSEL = 334, // 0x14E
        GETCURSEL = 327, // 0x147
        DELETESTRING = 324, // 0x144
        RESETCONTENT = 331, // 0x14B
        GETCOUNT = 326, // 0x146
        GETLBTEXT = 328, // 0x148
        GETLBTEXTLEN = 329, // 0x149
    }

    export const enum CbnCode {
        SELCHANGE = 1, // 0x1
    }

    export const enum ProgressMsg {
        SETRANGE32 = 1030, // 0x406
        SETPOS = 1026, // 0x402
    }

    export const enum ProgressStyle {
        SMOOTH = 1, // 0x1
    }

    export const enum TrackBarStyle {
        HORZ = 0, // 0x0
        VERT = 2, // 0x2
        AUTOTICKS = 1, // 0x1
        TOOLTIPS = 256, // 0x100
        NOTICKS = 16, // 0x10
    }

    export const enum TbMsg {
        GETPOS = 1024, // 0x400
        SETPOS = 1029, // 0x405
        GETRANGEMIN = 1025, // 0x401
        GETRANGEMAX = 1026, // 0x402
        SETRANGE = 1030, // 0x406
        SETLINESIZE = 1047, // 0x417
        SETPAGESIZE = 1045, // 0x415
    }

    export const enum DtStyle {
        SHORTDATEFORMAT = 0, // 0x0
        LONGDATEFORMAT = 4, // 0x4
        TIMEFORMAT = 9, // 0x9
        UPDOWN = 1, // 0x1
        SHOWNONE = 2, // 0x2
    }

    export const enum DtMsg {
        GETSYSTEMTIME = 4097, // 0x1001
        SETSYSTEMTIME = 4098, // 0x1002
        SETFORMATW = 4146, // 0x1032
    }

    export const enum DtNotifyCode {
        DATETIMECHANGE = -759, // 0xFFFFFD09
    }

    export const enum DtFlag {
        GDT_VALID = 0, // 0x0
        GDT_NONE = 1, // 0x1
    }

    export const enum TreeViewStyle {
        HASBUTTONS = 1, // 0x1
        HASLINES = 2, // 0x2
        LINESATROOT = 4, // 0x4
        SHOWSELALWAYS = 32, // 0x20
        CHECKBOXES = 256, // 0x100
        NOTOOLTIPS = 128, // 0x80
        TRACKSELECT = 512, // 0x200
    }

    export const enum TvInsertAfter {
        ROOT = -65536, // 0xFFFF0000
        LAST = -65534, // 0xFFFF0002
        FIRST = -65535, // 0xFFFF0001
        SORT = -65533, // 0xFFFF0003
    }

    export const enum TvMsg {
        INSERTITEMW = 4402, // 0x1132
        DELETEITEM = 4353, // 0x1101
        EXPAND = 4354, // 0x1102
        GETNEXTITEM = 4362, // 0x110A
        SELECTITEM = 4363, // 0x110B
        GETITEMW = 4414, // 0x113E
        SETITEMW = 4415, // 0x113F
        GETCOUNT = 4357, // 0x1105
        ENSUREVISIBLE = 4372, // 0x1114
        SETITEMHEIGHT = 4379, // 0x111B
        SETEXTENDEDSTYLE = 4396, // 0x112C
    }

    export const enum TvExStyle {
        DOUBLEBUFFER = 4, // 0x4
    }

    export const enum TvNotifyCode {
        SELCHANGEDW = -451, // 0xFFFFFE3D
        ITEMEXPANDEDW = -455, // 0xFFFFFE39
        ITEMEXPANDINGW = -454, // 0xFFFFFE3A
    }

    export const enum TvExpandCmd {
        COLLAPSE = 1, // 0x1
        EXPAND = 2, // 0x2
        TOGGLE = 3, // 0x3
        COLLAPSERESET = 32768, // 0x8000
    }

    export const enum TvIfFlag {
        TEXT = 1, // 0x1
        IMAGE = 2, // 0x2
        SELECTEDIMAGE = 32, // 0x20
        STATE = 8, // 0x8
        CHILDREN = 64, // 0x40
        PARAM = 4, // 0x4
        HANDLE = 16, // 0x10
    }

    export const enum TvGnRelative {
        ROOT = 0, // 0x0
        NEXT = 1, // 0x1
        PREVIOUS = 2, // 0x2
        PARENT = 3, // 0x3
        CHILD = 4, // 0x4
        FIRSTVISIBLE = 5, // 0x5
        LASTVISIBLE = 10, // 0xA
        CARET = 9, // 0x9
        DROPHILITE = 8, // 0x8
    }

    // GetWindowLongPtr/GWL 索引
    export const enum Gwlp {
        WNDPROC = -4, // 0xFFFFFFFC
        HINSTANCE = -6, // 0xFFFFFFFA
        HWNDPARENT = -8, // 0xFFFFFFF8
        USERDATA = -21, // 0xFFFFFFEB
        ID = -12, // 0xFFFFFFF4
        STYLE = -16, // 0xFFFFFFF0
    }

    export const enum SysLinkMsg {
        GETIDEALHEIGHT = 1793, // 0x701
        SETITEM = 1794, // 0x702
        GETITEM = 1795, // 0x703
        HITTEST = 1792, // 0x700
    }

    export const enum SysLinkNotifyCode {
        CLICK = -2, // 0xFFFFFFFE
        RETURN = -4, // 0xFFFFFFFC
    }

    export const enum LinkStyle {
        IGNORERETURN = 2, // 0x2
        TRANSPARENT = 1, // 0x1
        USEVISUALSTYLE = 8, // 0x8
    }

    export const enum TtMsg {
        ACTIVATE = 1025, // 0x401
        ADDTOOLW = 1074, // 0x432
        DELTOOLW = 1075, // 0x433
        SETTOOLINFOW = 1078, // 0x436
        UPDATETIPTEXTW = 1081, // 0x439
        SETMAXTIPWIDTH = 1048, // 0x418
        SETDELAYTIME = 1027, // 0x403
        POPUP = 1058, // 0x422
    }

    export const enum TooltipStyle {
        ALWAYSTIP = 1, // 0x1
        NOPREFIX = 2, // 0x2
        BALLOON = 64, // 0x40
        CLOSE = 128, // 0x80
        USEVISUALSTYLE = 256, // 0x100
    }

    export const enum CreatePos {
        USEDEFAULT = -2147483648, // 0x80000000
    }

    export const enum TtToolFlag {
        SUBCLASS = 16, // 0x10
        IDISHWND = 1, // 0x1
        CENTERTIP = 2, // 0x2
        TRACK = 32, // 0x20
        ABSOLUTE = 128, // 0x80
        TRANSPARENT = 256, // 0x100
        DI_SETITEM = 32768, // 0x8000
    }

    export const enum RasterOp {
        SRCCOPY = 13369376, // 0xCC0020
        WHITENESS = 16711778, // 0xFF0062
        BLACKNESS = 66, // 0x42
    }

    export const enum OpenFileNameFlag {
        OVERWRITEPROMPT = 2, // 0x2
        EXPLORER = 524288, // 0x80000
        HIDEREADONLY = 4, // 0x4
        NOCHANGEDIR = 8, // 0x8
        ALLOWMULTISELECT = 512, // 0x200
        PATHMUSTEXIST = 2048, // 0x800
        FILEMUSTEXIST = 4096, // 0x1000
        NOREADONLYRETURN = 32768, // 0x8000
    }

    // Registry
    export const enum HKey {
        CURRENT_USER = -2147483647, // 0x80000001
        LOCAL_MACHINE = -2147483646, // 0x80000002
    }

    export const enum RegAccess {
        SET_VALUE = 2, // 0x2
        READ = 131097, // 0x20019
    }

    export const enum RegType {
        SZ = 1, // 0x1
    }

    // Printer
    export const enum PrinterEnum {
        LOCAL = 2, // 0x2
        CONNECTIONS = 4, // 0x4
    }

    // DeviceCaps
    export const enum DeviceCap {
        HORZRES = 8, // 0x8
        VERTRES = 10, // 0xA
        LOGPIXELSX = 88, // 0x58
        LOGPIXELSY = 90, // 0x5A
    }

    // Static controls
    export const enum StaticMsg {
        SETICON = 368, // 0x170
        SETIMAGE = 370, // 0x172
        GETICON = 369, // 0x171
        GETIMAGE = 371, // 0x173
    }

    export const enum StaticStyleEx {
        LEFT = 0, // 0x0
        CENTER = 1, // 0x1
        RIGHT = 2, // 0x2
        ICON = 3, // 0x3
        BLACKRECT = 4, // 0x4
        GRAYRECT = 5, // 0x5
        WHITERECT = 6, // 0x6
        BLACKFRAME = 7, // 0x7
        GRAYFRAME = 8, // 0x8
        WHITEFRAME = 9, // 0x9
        SIMPLE = 11, // 0xB
        LEFTNOWORDWRAP = 12, // 0xC
        OWNERDRAW = 13, // 0xD
        BITMAP = 14, // 0xE
        ETCHEDHORZ = 16, // 0x10
        ETCHEDVERT = 17, // 0x11
        ETCHEDFRAME = 18, // 0x12
        NOTIFY = 256, // 0x100
        CENTERIMAGE = 512, // 0x200
        RIGHTJUST = 1024, // 0x400
        SUNKEN = 4096, // 0x1000
        ENDELLIPSIS = 16384, // 0x4000
        PATHELLIPSIS = 32768, // 0x8000
        WORDELLIPSIS = 49152, // 0xC000
        REALSIZEIMAGE = 2048, // 0x800
    }

    export const enum ImageType {
        BITMAP = 0, // 0x0
        ICON = 1, // 0x1
        CURSOR = 2, // 0x2
    }

    export const enum LoadImageFlag {
        DEFAULTCOLOR = 0, // 0x0
        MONOCHROME = 1, // 0x1
        COLOR = 2, // 0x2
        COPYRETURNORG = 4, // 0x4
        COPYDELETEORG = 8, // 0x8
        LOADFROMFILE = 16, // 0x10
        LOADTRANSPARENT = 32, // 0x20
        DEFAULTSIZE = 64, // 0x40
        VGACOLOR = 128, // 0x80
        CREATEDIBSECTION = 8192, // 0x2000
        COPYFROMRESOURCE = 16384, // 0x4000
        SHARED = 32768, // 0x8000
    }

    export const enum IDI {
        APPLICATION = 32512, // 0x7F00
        ERROR = 32513, // 0x7F01
        INFORMATION = 32516, // 0x7F04
        QUESTION = 32514, // 0x7F02
        WARNING = 32515, // 0x7F03
        WINLOGO = 32517, // 0x7F05
        SHIELD = 32518, // 0x7F06
    }

    export const enum DrawTextFlag {
        CALCRECT = 1024, // 0x400
    }

    // Process
    export const enum ProcessCreationFlag {
        NO_WINDOW = 134217728, // 0x8000000
    }

    // Error codes
    export const enum ErrorCode {
        FILE_NOT_FOUND = 2, // 0x2
        PATH_NOT_FOUND = 3, // 0x3
        ACCESS_DENIED = 5, // 0x5
        INVALID_HANDLE = 6, // 0x6
        NOT_ENOUGH_MEMORY = 8, // 0x8
        OUTOFMEMORY = 14, // 0xE
        INVALID_PARAMETER = 87, // 0x57
        ALREADY_EXISTS = 183, // 0xB7
        INSUFFICIENT_BUFFER = 122, // 0x7A
        MORE_DATA = 234, // 0xEA
        NO_DATA = 232, // 0xE8
    }

    // Power management
    export const enum PowerBroadcast {
        APMQUERYSUSPEND = 0, // 0x0
        APMQUERYSTANDBY = 1, // 0x1
        APMQUERYSUSPENDFAILED = 2, // 0x2
        APMQUERYSTANDBYFAILED = 3, // 0x3
        APMSUSPEND = 4, // 0x4
        APMSTANDBY = 5, // 0x5
        APMRESUMECRITICAL = 6, // 0x6
        APMRESUMESUSPEND = 7, // 0x7
        APMRESUMEAUTOMATIC = 18, // 0x12
        APMBATTERYLOW = 9, // 0x9
        APMPOWERSTATUSCHANGE = 10, // 0xA
        APMOEMEVENT = 11, // 0xB
        POWERSETTINGCHANGE = 32787, // 0x8013
    }

    // DevMode
    export const enum DevMode {
        DUPLEX = 4096, // 0x1000
        OUT_BUFFER = 2, // 0x2
    }

    // COM GUIDs
    export const enum Guid {
        IID_ISHELLLINKW = '{000214F9-0000-0000-C000-000000000046}',
        IID_IPERSISTFILE = '{0000010B-0000-0000-C000-000000000046}',
    }

}

declare module "sock" {

    export const enum AddrFamily {
        AF_INET = 2, // 0x2
        AF_INET6 = 23, // 0x17
    }

    export const enum SockType {
        SOCK_STREAM = 1, // 0x1
        SOCK_DGRAM = 2, // 0x2
    }

    export const enum Protocol {
        IPPROTO_TCP = 6, // 0x6
        IPPROTO_UDP = 17, // 0x11
    }

    export const enum Shutdown {
        SD_RECEIVE = 0, // 0x0
        SD_SEND = 1, // 0x1
        SD_BOTH = 2, // 0x2
    }

    export const enum FdEvent {
        FD_ACCEPT = 8, // 0x8
        FD_READ = 1, // 0x1
        FD_WRITE = 2, // 0x2
        FD_CONNECT = 16, // 0x10
        FD_CLOSE = 32, // 0x20
    }

}

declare module "wolfssl" {

    export const enum VerifyMode {
        SSL_VERIFY_NONE = 0, // 0x0
        SSL_VERIFY_PEER = 1, // 0x1
    }

    export const enum SniType {
        WOLFSSL_SNI_HOST_NAME = 0, // 0x0
    }

    export const enum FileType {
        SSL_FILETYPE_PEM = 1, // 0x1
    }

    export const enum ReturnCode {
        SSL_SUCCESS = 1, // 0x1
    }

    export const enum ErrorCode {
        WOLFSSL_ERROR_WANT_READ = 2, // 0x2
        WOLFSSL_ERROR_WANT_WRITE = 3, // 0x3
    }

}
