services:
  dev:
    image: localhost/quickwin-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    pull_policy: never
    container_name: quickwin-dev
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - ..:/workspace:Z
    ports:
      - "6080:6080"
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: bash
