#define INITGUID
#include <winsock2.h>
#include <windows.h>
#include <commctrl.h>
#include <shellapi.h>
#include <commdlg.h>
#include <winspool.h>
#include <shobjidl.h>
#include <wolfssl/options.h>
#include <wolfssl/ssl.h>
#include <stdio.h>

#define DEC(ts, c) printf("        %s = %d, // 0x%X\n", #ts, (int)(c), (unsigned)(c));
#define DEC_GUID(name, guid) do { \
    GUID _g = (guid); \
    printf("        %s = '{%08lX-%04hX-%04hX-%02X%02X-%02X%02X%02X%02X%02X%02X}',\n", \
        name, _g.Data1, _g.Data2, _g.Data3, \
        _g.Data4[0], _g.Data4[1], _g.Data4[2], _g.Data4[3], \
        _g.Data4[4], _g.Data4[5], _g.Data4[6], _g.Data4[7]); \
} while(0)

static void print_enums(void) {
    printf("// Auto-generated by tools/gen_const.c. DO NOT EDIT.\n");
    printf("// Regenerate with: make const\n\n");
    /* gui */
    printf("declare module \"gui\" {\n\n");

    printf("    export const enum GetWindowCmd {\n");
    DEC(FIRST, GW_HWNDFIRST);
    DEC(LAST, GW_HWNDLAST);
    DEC(NEXT, GW_HWNDNEXT);
    DEC(PREV, GW_HWNDPREV);
    DEC(OWNER, GW_OWNER);
    DEC(CHILD, GW_CHILD);
    printf("    }\n\n");

    printf("    export const enum SetWindowPosFlag {\n");
    DEC(SWP_NOSIZE, SWP_NOSIZE);
    DEC(SWP_NOMOVE, SWP_NOMOVE);
    DEC(SWP_NOZORDER, SWP_NOZORDER);
    DEC(SWP_NOACTIVATE, SWP_NOACTIVATE);
    DEC(SWP_SHOWWINDOW, SWP_SHOWWINDOW);
    DEC(SWP_HIDEWINDOW, SWP_HIDEWINDOW);
    DEC(SWP_FRAMECHANGED, SWP_FRAMECHANGED);
    printf("    }\n\n");

    printf("    export const enum SetWindowPosHwnd {\n");
    DEC(TOP, HWND_TOP);
    DEC(TOPMOST, HWND_TOPMOST);
    DEC(NOTOPMOST, HWND_NOTOPMOST);
    printf("    }\n\n");

    printf("    export const enum NotifyIconCmd {\n");
    DEC(ADD, NIM_ADD);
    DEC(MODIFY, NIM_MODIFY);
    DEC(DELETE, NIM_DELETE);
    printf("    }\n\n");

    printf("    export const enum NotifyIconFlag {\n");
    DEC(MESSAGE, NIF_MESSAGE);
    DEC(ICON, NIF_ICON);
    DEC(TIP, NIF_TIP);
    printf("    }\n\n");

    printf("    export const enum MenuFlag {\n");
    DEC(STRING, MF_STRING);
    DEC(SEPARATOR, MF_SEPARATOR);
    DEC(CHECKED, MF_CHECKED);
    DEC(GRAYED, MF_GRAYED);
    DEC(DISABLED, MF_DISABLED);
    DEC(POPUP, MF_POPUP);
    printf("    }\n\n");

    printf("    export const enum WindowStyle {\n");
    DEC(OVERLAPPEDWINDOW, WS_OVERLAPPEDWINDOW);
    DEC(CHILD, WS_CHILD);
    DEC(POPUP, WS_POPUP);
    DEC(VISIBLE, WS_VISIBLE);
    DEC(BORDER, WS_BORDER);
    DEC(HSCROLL, WS_HSCROLL);
    DEC(VSCROLL, WS_VSCROLL);
    DEC(CLIPCHILDREN, WS_CLIPCHILDREN);
    DEC(TABSTOP, WS_TABSTOP);
    DEC(GROUP, WS_GROUP);
    printf("    }\n\n");

    printf("    export const enum WmMsg {\n");
    DEC(NULL, WM_NULL);
    DEC(CREATE, WM_CREATE);
    DEC(DESTROY, WM_DESTROY);
    DEC(MOVE, WM_MOVE);
    DEC(SIZE, WM_SIZE);
    DEC(ACTIVATE, WM_ACTIVATE);
    DEC(SETFOCUS, WM_SETFOCUS);
    DEC(KILLFOCUS, WM_KILLFOCUS);
    DEC(ENABLE, WM_ENABLE);
    DEC(SETREDRAW, WM_SETREDRAW);
    DEC(SETTEXT, WM_SETTEXT);
    DEC(GETTEXT, WM_GETTEXT);
    DEC(GETTEXTLENGTH, WM_GETTEXTLENGTH);
    DEC(PAINT, WM_PAINT);
    DEC(CLOSE, WM_CLOSE);
    DEC(QUERYENDSESSION, WM_QUERYENDSESSION);
    DEC(QUIT, WM_QUIT);
    DEC(WINDOWPOSCHANGING, WM_WINDOWPOSCHANGING);
    DEC(WINDOWPOSCHANGED, WM_WINDOWPOSCHANGED);
    DEC(SYSCOMMAND, WM_SYSCOMMAND);
    DEC(TIMER, WM_TIMER);
    DEC(HSCROLL, WM_HSCROLL);
    DEC(VSCROLL, WM_VSCROLL);
    DEC(INITMENU, WM_INITMENU);
    DEC(INITMENUPOPUP, WM_INITMENUPOPUP);
    DEC(MOUSEWHEEL, WM_MOUSEWHEEL);
    DEC(MOUSEMOVE, WM_MOUSEMOVE);
    DEC(LBUTTONDOWN, WM_LBUTTONDOWN);
    DEC(LBUTTONUP, WM_LBUTTONUP);
    DEC(LBUTTONDBLCLK, WM_LBUTTONDBLCLK);
    DEC(RBUTTONDOWN, WM_RBUTTONDOWN);
    DEC(RBUTTONUP, WM_RBUTTONUP);
    DEC(RBUTTONDBLCLK, WM_RBUTTONDBLCLK);
    DEC(MBUTTONDOWN, WM_MBUTTONDOWN);
    DEC(MBUTTONUP, WM_MBUTTONUP);
    DEC(MBUTTONDBLCLK, WM_MBUTTONDBLCLK);
    DEC(MOUSEHOVER, WM_MOUSEHOVER);
    DEC(MOUSELEAVE, WM_MOUSELEAVE);
    DEC(KEYDOWN, WM_KEYDOWN);
    DEC(KEYUP, WM_KEYUP);
    DEC(CHAR, WM_CHAR);
    DEC(DEADCHAR, WM_DEADCHAR);
    DEC(SYSKEYDOWN, WM_SYSKEYDOWN);
    DEC(SYSKEYUP, WM_SYSKEYUP);
    DEC(SYSCHAR, WM_SYSCHAR);
    DEC(SYSDEADCHAR, WM_SYSDEADCHAR);
    DEC(UNICHAR, WM_UNICHAR);
    DEC(COMMAND, WM_COMMAND);
    DEC(MENUSELECT, WM_MENUSELECT);
    DEC(MENUCHAR, WM_MENUCHAR);
    DEC(ENTERIDLE, WM_ENTERIDLE);
    DEC(MENURBUTTONUP, WM_MENURBUTTONUP);
    DEC(MENUCOMMAND, WM_MENUCOMMAND);
    DEC(UNINITMENUPOPUP, WM_UNINITMENUPOPUP);
    DEC(ENTERMENULOOP, WM_ENTERMENULOOP);
    DEC(EXITMENULOOP, WM_EXITMENULOOP);
    DEC(SETFONT, WM_SETFONT);
    DEC(GETFONT, WM_GETFONT);
    DEC(SETHOTKEY, WM_SETHOTKEY);
    DEC(GETHOTKEY, WM_GETHOTKEY);
    DEC(DRAWITEM, WM_DRAWITEM);
    DEC(MEASUREITEM, WM_MEASUREITEM);
    DEC(DELETEITEM, WM_DELETEITEM);
    DEC(COMPAREITEM, WM_COMPAREITEM);
    DEC(NCCREATE, WM_NCCREATE);
    DEC(NCDESTROY, WM_NCDESTROY);
    DEC(NCCALCSIZE, WM_NCCALCSIZE);
    DEC(NCHITTEST, WM_NCHITTEST);
    DEC(NCPAINT, WM_NCPAINT);
    DEC(NCACTIVATE, WM_NCACTIVATE);
    DEC(NCMOUSEMOVE, WM_NCMOUSEMOVE);
    DEC(NCLBUTTONDOWN, WM_NCLBUTTONDOWN);
    DEC(NCLBUTTONUP, WM_NCLBUTTONUP);
    DEC(NCLBUTTONDBLCLK, WM_NCLBUTTONDBLCLK);
    DEC(NCRBUTTONDOWN, WM_NCRBUTTONDOWN);
    DEC(NCRBUTTONUP, WM_NCRBUTTONUP);
    DEC(NCRBUTTONDBLCLK, WM_NCRBUTTONDBLCLK);
    DEC(NCMBUTTONDOWN, WM_NCMBUTTONDOWN);
    DEC(NCMBUTTONUP, WM_NCMBUTTONUP);
    DEC(NCMBUTTONDBLCLK, WM_NCMBUTTONDBLCLK);
    DEC(NCXBUTTONDOWN, WM_NCXBUTTONDOWN);
    DEC(NCXBUTTONUP, WM_NCXBUTTONUP);
    DEC(NCXBUTTONDBLCLK, WM_NCXBUTTONDBLCLK);
    DEC(NCMOUSELEAVE, WM_NCMOUSELEAVE);
    DEC(GETDLGCODE, WM_GETDLGCODE);
    DEC(SETCURSOR, WM_SETCURSOR);
    DEC(MOUSEACTIVATE, WM_MOUSEACTIVATE);
    DEC(CHILDACTIVATE, WM_CHILDACTIVATE);
    DEC(GETMINMAXINFO, WM_GETMINMAXINFO);
    DEC(DROPFILES, WM_DROPFILES);
    DEC(ENTERSIZEMOVE, WM_ENTERSIZEMOVE);
    DEC(EXITSIZEMOVE, WM_EXITSIZEMOVE);
    DEC(SIZING, WM_SIZING);
    DEC(MOVING, WM_MOVING);
    DEC(CAPTURECHANGED, WM_CAPTURECHANGED);
    DEC(GETICON, WM_GETICON);
    DEC(SETICON, WM_SETICON);
    DEC(ERASEBKGND, WM_ERASEBKGND);
    DEC(SYSCOLORCHANGE, WM_SYSCOLORCHANGE);
    DEC(HSCROLLCLIPBOARD, WM_HSCROLLCLIPBOARD);
    DEC(VSCROLLCLIPBOARD, WM_VSCROLLCLIPBOARD);
    DEC(QUERYUISTATE, WM_QUERYUISTATE);
    DEC(CONTEXTMENU, WM_CONTEXTMENU);
    DEC(NOTIFY, WM_NOTIFY);
    DEC(STYLECHANGING, WM_STYLECHANGING);
    DEC(STYLECHANGED, WM_STYLECHANGED);
    DEC(SHOWWINDOW, WM_SHOWWINDOW);
    DEC(FONTCHANGE, WM_FONTCHANGE);
    DEC(POWERBROADCAST, WM_POWERBROADCAST);
    DEC(IME_STARTCOMPOSITION, WM_IME_STARTCOMPOSITION);
    DEC(IME_ENDCOMPOSITION, WM_IME_ENDCOMPOSITION);
    DEC(IME_COMPOSITION, WM_IME_COMPOSITION);
    DEC(IME_SETCONTEXT, WM_IME_SETCONTEXT);
    DEC(IME_NOTIFY, WM_IME_NOTIFY);
    DEC(IME_CONTROL, WM_IME_CONTROL);
    DEC(IME_COMPOSITIONFULL, WM_IME_COMPOSITIONFULL);
    DEC(IME_SELECT, WM_IME_SELECT);
    DEC(IME_CHAR, WM_IME_CHAR);
    DEC(IME_REQUEST, WM_IME_REQUEST);
    DEC(IME_KEYDOWN, WM_IME_KEYDOWN);
    DEC(IME_KEYUP, WM_IME_KEYUP);
    DEC(TOUCH, WM_TOUCH);
    DEC(DISPLAYCHANGE, WM_DISPLAYCHANGE);
    DEC(THEMECHANGED, WM_THEMECHANGED);
    DEC(DWMCOLORIZATIONCOLORCHANGED, WM_DWMCOLORIZATIONCOLORCHANGED);
    DEC(USER, WM_USER);
    printf("    }\n\n");

    printf("    export const enum ScrollBar {\n");
    DEC(HORZ, SB_HORZ);
    DEC(VERT, SB_VERT);
    printf("    }\n\n");

    printf("    export const enum ScrollCmd {\n");
    DEC(LINEUP, SB_LINEUP);
    DEC(LINEDOWN, SB_LINEDOWN);
    DEC(PAGEUP, SB_PAGEUP);
    DEC(PAGEDOWN, SB_PAGEDOWN);
    DEC(THUMBTRACK, SB_THUMBTRACK);
    DEC(THUMBPOSITION, SB_THUMBPOSITION);
    DEC(TOP, SB_TOP);
    DEC(BOTTOM, SB_BOTTOM);
    DEC(ENDSCROLL, SB_ENDSCROLL);
    printf("    }\n\n");

    printf("    export const enum ScrollInfoFlag {\n");
    DEC(RANGE, SIF_RANGE);
    DEC(PAGE, SIF_PAGE);
    DEC(POS, SIF_POS);
    DEC(ALL, SIF_ALL);
    printf("    }\n\n");

    printf("    export const enum SysMetrics {\n");
    DEC(CXSCREEN, SM_CXSCREEN);
    DEC(CYSCREEN, SM_CYSCREEN);
    printf("    }\n\n");

    printf("    export const enum ButtonStyle {\n");
    DEC(PUSHBUTTON, BS_PUSHBUTTON);
    DEC(DEFPUSHBUTTON, BS_DEFPUSHBUTTON);
    DEC(CHECKBOX, BS_CHECKBOX);
    DEC(AUTOCHECKBOX, BS_AUTOCHECKBOX);
    DEC(AUTORADIOBUTTON, BS_AUTORADIOBUTTON);
    DEC(GROUPBOX, BS_GROUPBOX);
    printf("    }\n\n");

    printf("    export const enum MouseKeyFlag {\n");
    DEC(MK_SHIFT, MK_SHIFT);
    printf("    }\n\n");

    printf("    export const enum LbMsg {\n");
    DEC(ADDSTRING, LB_ADDSTRING);
    DEC(INSERTSTRING, LB_INSERTSTRING);
    DEC(DELETESTRING, LB_DELETESTRING);
    DEC(RESETCONTENT, LB_RESETCONTENT);
    DEC(SETTOPINDEX, LB_SETTOPINDEX);
    DEC(SETCURSEL, LB_SETCURSEL);
    DEC(GETCURSEL, LB_GETCURSEL);
    DEC(GETTEXT, LB_GETTEXT);
    DEC(GETTEXTLEN, LB_GETTEXTLEN);
    DEC(GETCOUNT, LB_GETCOUNT);
    printf("    }\n\n");

    printf("    export const enum StaticStyle {\n");
    DEC(LEFT, SS_LEFT);
    printf("    }\n\n");

    printf("    export const enum EditStyle {\n");
    DEC(LEFT, ES_LEFT);
    DEC(MULTILINE, ES_MULTILINE);
    DEC(PASSWORD, ES_PASSWORD);
    DEC(AUTOVSCROLL, ES_AUTOVSCROLL);
    DEC(AUTOHSCROLL, ES_AUTOHSCROLL);
    DEC(READONLY, ES_READONLY);
    DEC(WANTRETURN, ES_WANTRETURN);
    DEC(NUMBER, ES_NUMBER);
    printf("    }\n\n");

    printf("    export const enum ComboBoxStyle {\n");
    DEC(DROPDOWNLIST, CBS_DROPDOWNLIST);
    DEC(HASSTRINGS, CBS_HASSTRINGS);
    printf("    }\n\n");

    printf("    export const enum ListBoxStyle {\n");
    DEC(NOTIFY, LBS_NOTIFY);
    DEC(SORT, LBS_SORT);
    DEC(MULTIPLESEL, LBS_MULTIPLESEL);
    DEC(HASSTRINGS, LBS_HASSTRINGS);
    DEC(NOINTEGRALHEIGHT, LBS_NOINTEGRALHEIGHT);
    DEC(EXTENDEDSEL, LBS_EXTENDEDSEL);
    DEC(STANDARD, LBS_STANDARD);
    printf("    }\n\n");

    printf("    export const enum LbnCode {\n");
    DEC(SELCHANGE, LBN_SELCHANGE);
    printf("    }\n\n");

    printf("    export const enum TabStyle {\n");
    DEC(FOCUSNEVER, TCS_FOCUSNEVER);
    DEC(FIXEDWIDTH, TCS_FIXEDWIDTH);
    printf("    }\n\n");

    printf("    export const enum TcMsg {\n");
    DEC(GETITEMCOUNT, TCM_GETITEMCOUNT);
    DEC(INSERTITEMW, TCM_INSERTITEMW);
    DEC(DELETEITEM, TCM_DELETEITEM);
    DEC(DELETEALLITEMS, TCM_DELETEALLITEMS);
    DEC(GETCURSEL, TCM_GETCURSEL);
    DEC(SETCURSEL, TCM_SETCURSEL);
    printf("    }\n\n");

    printf("    export const enum TcNotifyCode {\n");
    DEC(SELCHANGE, TCN_SELCHANGE);
    DEC(SELCHANGING, TCN_SELCHANGING);
    printf("    }\n\n");

    printf("    export const enum TcItemFlag {\n");
    DEC(TEXT, TCIF_TEXT);
    printf("    }\n\n");

    printf("    export const enum ListViewStyle {\n");
    DEC(REPORT, LVS_REPORT);
    DEC(SINGLESEL, LVS_SINGLESEL);
    DEC(SHOWSELALWAYS, LVS_SHOWSELALWAYS);
    DEC(NOSORTHEADER, LVS_NOSORTHEADER);
    printf("    }\n\n");

    printf("    export const enum LvExStyle {\n");
    DEC(GRIDLINES, LVS_EX_GRIDLINES);
    DEC(CHECKBOXES, LVS_EX_CHECKBOXES);
    DEC(TRACKSELECT, LVS_EX_TRACKSELECT);
    DEC(HEADERDRAGDROP, LVS_EX_HEADERDRAGDROP);
    DEC(FULLROWSELECT, LVS_EX_FULLROWSELECT);
    DEC(DOUBLEBUFFER, LVS_EX_DOUBLEBUFFER);
    printf("    }\n\n");

    printf("    export const enum LvMsg {\n");
    DEC(GETITEMCOUNT, LVM_GETITEMCOUNT);
    DEC(DELETEALLITEMS, LVM_DELETEALLITEMS);
    DEC(GETNEXTITEM, LVM_GETNEXTITEM);
    DEC(GETITEMSTATE, LVM_GETITEMSTATE);
    DEC(SETITEMSTATE, LVM_SETITEMSTATE);
    DEC(GETSELECTEDCOUNT, LVM_GETSELECTEDCOUNT);
    DEC(SETEXTENDEDLISTVIEWSTYLE, LVM_SETEXTENDEDLISTVIEWSTYLE);
    DEC(INSERTCOLUMNW, LVM_INSERTCOLUMNW);
    DEC(GETSELECTIONMARK, LVM_GETSELECTIONMARK);
    DEC(INSERTITEMW, LVM_INSERTITEMW);
    DEC(SETITEMW, LVM_SETITEMW);
    DEC(ENSUREVISIBLE, LVM_ENSUREVISIBLE);
    DEC(SETCOLUMNWIDTH, LVM_SETCOLUMNWIDTH);
    DEC(DELETECOLUMN, LVM_DELETECOLUMN);
    DEC(GETHEADER, LVM_GETHEADER);
    DEC(SUBITEMHITTEST, LVM_SUBITEMHITTEST);
    printf("    }\n\n");

    printf("    export const enum HitTest {\n");
    DEC(CLIENT, HTCLIENT);
    printf("    }\n\n");

    printf("    export const enum StandardCursor {\n");
    DEC(HAND, IDC_HAND);
    printf("    }\n\n");

    printf("    export const enum LvItemFlag {\n");
    DEC(TEXT, LVIF_TEXT);
    DEC(STATE, LVIF_STATE);
    printf("    }\n\n");

    printf("    export const enum LvItemState {\n");
    DEC(FOCUSED, LVIS_FOCUSED);
    DEC(SELECTED, LVIS_SELECTED);
    printf("    }\n\n");

    printf("    export const enum LvColumnMask {\n");
    DEC(FORMAT, LVCF_FMT);
    DEC(WIDTH, LVCF_WIDTH);
    DEC(TEXT, LVCF_TEXT);
    printf("    }\n\n");

    printf("    export const enum LvColumnFormat {\n");
    DEC(LEFT, LVCFMT_LEFT);
    DEC(CENTER, LVCFMT_CENTER);
    DEC(RIGHT, LVCFMT_RIGHT);
    printf("    }\n\n");

    printf("    export const enum FontWeight {\n");
    DEC(NORMAL, FW_NORMAL);
    DEC(BOLD, FW_BOLD);
    printf("    }\n\n");

    printf("    export const enum LvNavFlag {\n");
    DEC(SELECTED, LVNI_SELECTED);
    printf("    }\n\n");

    printf("    export const enum LvColumnWidthCmd {\n");
    DEC(AUTOSIZE, LVSCW_AUTOSIZE);
    DEC(AUTOSIZE_USEHEADER, LVSCW_AUTOSIZE_USEHEADER);
    printf("    }\n\n");

    printf("    export const enum HdmMsg {\n");
    DEC(GETITEMCOUNT, HDM_GETITEMCOUNT);
    printf("    }\n\n");

    printf("    export const enum LvNotifyCode {\n");
    DEC(ITEMCHANGING, LVN_ITEMCHANGING);
    DEC(ITEMCHANGED, LVN_ITEMCHANGED);
    DEC(CLICK, NM_CLICK);
    DEC(CUSTOMDRAW, NM_CUSTOMDRAW);
    printf("    }\n\n");

    printf("    export const enum CustomDrawStage {\n");
    DEC(PREPAINT, CDDS_PREPAINT);
    DEC(ITEM, CDDS_ITEM);
    DEC(SUBITEM, CDDS_SUBITEM);
    DEC(ITEMPREPAINT, CDDS_ITEMPREPAINT);
    DEC(SUBITEMPREPAINT, CDDS_ITEMPREPAINT | CDDS_SUBITEM);
    printf("    }\n\n");

    printf("    export const enum CustomDrawFlag {\n");
    DEC(DODEFAULT, CDRF_DODEFAULT);
    DEC(NEWFONT, CDRF_NEWFONT);
    DEC(NOTIFYITEMDRAW, CDRF_NOTIFYITEMDRAW);
    DEC(NOTIFYSUBITEMDRAW, CDRF_NOTIFYSUBITEMDRAW);
    printf("    }\n\n");

    printf("    export const enum ShowWindowCmd {\n");
    DEC(HIDE, SW_HIDE);
    DEC(SHOWNORMAL, SW_SHOWNORMAL);
    DEC(SHOWMINIMIZED, SW_SHOWMINIMIZED);
    DEC(SHOWMAXIMIZED, SW_SHOWMAXIMIZED);
    DEC(SHOWNOACTIVATE, SW_SHOWNOACTIVATE);
    DEC(SHOW, SW_SHOW);
    DEC(MINIMIZE, SW_MINIMIZE);
    DEC(SHOWMINNOACTIVE, SW_SHOWMINNOACTIVE);
    DEC(SHOWNA, SW_SHOWNA);
    DEC(RESTORE, SW_RESTORE);
    DEC(SHOWDEFAULT, SW_SHOWDEFAULT);
    DEC(FORCEMINIMIZE, SW_FORCEMINIMIZE);
    printf("    }\n\n");

    printf("    export const enum ButtonMsg {\n");
    DEC(GETCHECK, BM_GETCHECK);
    DEC(SETCHECK, BM_SETCHECK);
    printf("    }\n\n");

    printf("    export const enum ButtonCheckState {\n");
    DEC(UNCHECKED, BST_UNCHECKED);
    DEC(CHECKED, BST_CHECKED);
    printf("    }\n\n");

    printf("    export const enum ButtonExtMsg {\n");
    DEC(GETIDEALSIZE, BCM_GETIDEALSIZE);
    printf("    }\n\n");

    printf("    export const enum EditMsg {\n");
    DEC(GETSEL, EM_GETSEL);
    DEC(SETSEL, EM_SETSEL);
    DEC(SETCUEBANNER, EM_SETCUEBANNER);
    DEC(SETPASSWORDCHAR, EM_SETPASSWORDCHAR);
    printf("    }\n\n");

    printf("    export const enum EditNotify {\n");
    DEC(CHANGE, EN_CHANGE);
    printf("    }\n\n");

    printf("    export const enum ComboBoxMsg {\n");
    DEC(ADDSTRING, CB_ADDSTRING);
    DEC(SETCURSEL, CB_SETCURSEL);
    DEC(GETCURSEL, CB_GETCURSEL);
    DEC(DELETESTRING, CB_DELETESTRING);
    DEC(RESETCONTENT, CB_RESETCONTENT);
    DEC(GETCOUNT, CB_GETCOUNT);
    DEC(GETLBTEXT, CB_GETLBTEXT);
    DEC(GETLBTEXTLEN, CB_GETLBTEXTLEN);
    printf("    }\n\n");

    printf("    export const enum CbnCode {\n");
    DEC(SELCHANGE, CBN_SELCHANGE);
    printf("    }\n\n");

    printf("    export const enum ProgressMsg {\n");
    DEC(SETRANGE32, PBM_SETRANGE32);
    DEC(SETPOS, PBM_SETPOS);
    printf("    }\n\n");

    printf("    export const enum ProgressStyle {\n");
    DEC(SMOOTH, PBS_SMOOTH);
    printf("    }\n\n");

    printf("    export const enum TrackBarStyle {\n");
    DEC(HORZ, TBS_HORZ);
    DEC(VERT, TBS_VERT);
    DEC(AUTOTICKS, TBS_AUTOTICKS);
    DEC(TOOLTIPS, TBS_TOOLTIPS);
    DEC(NOTICKS, TBS_NOTICKS);
    printf("    }\n\n");

    printf("    export const enum TbMsg {\n");
    DEC(GETPOS, TBM_GETPOS);
    DEC(SETPOS, TBM_SETPOS);
    DEC(GETRANGEMIN, TBM_GETRANGEMIN);
    DEC(GETRANGEMAX, TBM_GETRANGEMAX);
    DEC(SETRANGE, TBM_SETRANGE);
    DEC(SETLINESIZE, TBM_SETLINESIZE);
    DEC(SETPAGESIZE, TBM_SETPAGESIZE);
    printf("    }\n\n");

    printf("    export const enum DtStyle {\n");
    DEC(SHORTDATEFORMAT, DTS_SHORTDATEFORMAT);
    DEC(LONGDATEFORMAT, DTS_LONGDATEFORMAT);
    DEC(TIMEFORMAT, DTS_TIMEFORMAT);
    DEC(UPDOWN, DTS_UPDOWN);
    DEC(SHOWNONE, DTS_SHOWNONE);
    printf("    }\n\n");

    printf("    export const enum DtMsg {\n");
    DEC(GETSYSTEMTIME, DTM_GETSYSTEMTIME);
    DEC(SETSYSTEMTIME, DTM_SETSYSTEMTIME);
    DEC(SETFORMATW, DTM_SETFORMATW);
    printf("    }\n\n");

    printf("    export const enum DtNotifyCode {\n");
    DEC(DATETIMECHANGE, DTN_DATETIMECHANGE);
    printf("    }\n\n");

    printf("    export const enum DtFlag {\n");
    DEC(GDT_VALID, GDT_VALID);
    DEC(GDT_NONE, GDT_NONE);
    printf("    }\n\n");

    printf("    export const enum TreeViewStyle {\n");
    DEC(HASBUTTONS, TVS_HASBUTTONS);
    DEC(HASLINES, TVS_HASLINES);
    DEC(LINESATROOT, TVS_LINESATROOT);
    DEC(SHOWSELALWAYS, TVS_SHOWSELALWAYS);
    DEC(CHECKBOXES, TVS_CHECKBOXES);
    DEC(NOTOOLTIPS, TVS_NOTOOLTIPS);
    DEC(TRACKSELECT, TVS_TRACKSELECT);
    printf("    }\n\n");

    printf("    export const enum TvInsertAfter {\n");
    DEC(ROOT, TVI_ROOT);
    DEC(LAST, TVI_LAST);
    DEC(FIRST, TVI_FIRST);
    DEC(SORT, TVI_SORT);
    printf("    }\n\n");

    printf("    export const enum TvMsg {\n");
    DEC(INSERTITEMW, TVM_INSERTITEMW);
    DEC(DELETEITEM, TVM_DELETEITEM);
    DEC(EXPAND, TVM_EXPAND);
    DEC(GETNEXTITEM, TVM_GETNEXTITEM);
    DEC(SELECTITEM, TVM_SELECTITEM);
    DEC(GETITEMW, TVM_GETITEMW);
    DEC(SETITEMW, TVM_SETITEMW);
    DEC(GETCOUNT, TVM_GETCOUNT);
    DEC(ENSUREVISIBLE, TVM_ENSUREVISIBLE);
    DEC(SETITEMHEIGHT, TVM_SETITEMHEIGHT);
    DEC(SETEXTENDEDSTYLE, TVM_SETEXTENDEDSTYLE);
    printf("    }\n\n");

    printf("    export const enum TvExStyle {\n");
    DEC(DOUBLEBUFFER, TVS_EX_DOUBLEBUFFER);
    printf("    }\n\n");

    printf("    export const enum TvNotifyCode {\n");
    DEC(SELCHANGEDW, TVN_SELCHANGEDW);
    DEC(ITEMEXPANDEDW, TVN_ITEMEXPANDEDW);
    DEC(ITEMEXPANDINGW, TVN_ITEMEXPANDINGW);
    printf("    }\n\n");

    printf("    export const enum TvExpandCmd {\n");
    DEC(COLLAPSE, TVE_COLLAPSE);
    DEC(EXPAND, TVE_EXPAND);
    DEC(TOGGLE, TVE_TOGGLE);
    DEC(COLLAPSERESET, TVE_COLLAPSERESET);
    printf("    }\n\n");

    printf("    export const enum TvIfFlag {\n");
    DEC(TEXT, TVIF_TEXT);
    DEC(IMAGE, TVIF_IMAGE);
    DEC(SELECTEDIMAGE, TVIF_SELECTEDIMAGE);
    DEC(STATE, TVIF_STATE);
    DEC(CHILDREN, TVIF_CHILDREN);
    DEC(PARAM, TVIF_PARAM);
    DEC(HANDLE, TVIF_HANDLE);
    printf("    }\n\n");

    printf("    export const enum TvGnRelative {\n");
    DEC(ROOT, TVGN_ROOT);
    DEC(NEXT, TVGN_NEXT);
    DEC(PREVIOUS, TVGN_PREVIOUS);
    DEC(PARENT, TVGN_PARENT);
    DEC(CHILD, TVGN_CHILD);
    DEC(FIRSTVISIBLE, TVGN_FIRSTVISIBLE);
    DEC(LASTVISIBLE, TVGN_LASTVISIBLE);
    DEC(CARET, TVGN_CARET);
    DEC(DROPHILITE, TVGN_DROPHILITE);
    printf("    }\n\n");

    printf("    // GetWindowLongPtr/GWL 索引\n");
    printf("    export const enum Gwlp {\n");
    DEC(WNDPROC, GWLP_WNDPROC);
    DEC(HINSTANCE, GWLP_HINSTANCE);
    DEC(HWNDPARENT, GWLP_HWNDPARENT);
    DEC(USERDATA, GWLP_USERDATA);
    DEC(ID, GWLP_ID);
    DEC(STYLE, GWL_STYLE);
    printf("    }\n\n");

    printf("    export const enum SysLinkMsg {\n");
    DEC(GETIDEALHEIGHT, LM_GETIDEALHEIGHT);
    DEC(SETITEM, LM_SETITEM);
    DEC(GETITEM, LM_GETITEM);
    DEC(HITTEST, LM_HITTEST);
    printf("    }\n\n");

    printf("    export const enum SysLinkNotifyCode {\n");
    DEC(CLICK, NM_CLICK);
    DEC(RETURN, NM_RETURN);
    printf("    }\n\n");

    printf("    export const enum LinkStyle {\n");
    DEC(IGNORERETURN, LWS_IGNORERETURN);
    DEC(TRANSPARENT, LWS_TRANSPARENT);
    DEC(USEVISUALSTYLE, LWS_USEVISUALSTYLE);
    printf("    }\n\n");

    printf("    export const enum TtMsg {\n");
    DEC(ACTIVATE, TTM_ACTIVATE);
    DEC(ADDTOOLW, TTM_ADDTOOLW);
    DEC(DELTOOLW, TTM_DELTOOLW);
    DEC(SETTOOLINFOW, TTM_SETTOOLINFOW);
    DEC(UPDATETIPTEXTW, TTM_UPDATETIPTEXTW);
    DEC(SETMAXTIPWIDTH, TTM_SETMAXTIPWIDTH);
    DEC(SETDELAYTIME, TTM_SETDELAYTIME);
    DEC(POPUP, TTM_POPUP);
    printf("    }\n\n");

    printf("    export const enum TooltipStyle {\n");
    DEC(ALWAYSTIP, TTS_ALWAYSTIP);
    DEC(NOPREFIX, TTS_NOPREFIX);
    DEC(BALLOON, TTS_BALLOON);
    DEC(CLOSE, TTS_CLOSE);
    DEC(USEVISUALSTYLE, TTS_USEVISUALSTYLE);
    printf("    }\n\n");

    printf("    export const enum CreatePos {\n");
    DEC(USEDEFAULT, CW_USEDEFAULT);
    printf("    }\n\n");

    printf("    export const enum TtToolFlag {\n");
    DEC(SUBCLASS, TTF_SUBCLASS);
    DEC(IDISHWND, TTF_IDISHWND);
    DEC(CENTERTIP, TTF_CENTERTIP);
    DEC(TRACK, TTF_TRACK);
    DEC(ABSOLUTE, TTF_ABSOLUTE);
    DEC(TRANSPARENT, TTF_TRANSPARENT);
    DEC(DI_SETITEM, TTF_DI_SETITEM);
    printf("    }\n\n");

    printf("    export const enum RasterOp {\n");
    DEC(SRCCOPY, SRCCOPY);
    DEC(WHITENESS, WHITENESS);
    DEC(BLACKNESS, BLACKNESS);
    printf("    }\n\n");

    printf("    export const enum OpenFileNameFlag {\n");
    DEC(OVERWRITEPROMPT, OFN_OVERWRITEPROMPT);
    DEC(EXPLORER, OFN_EXPLORER);
    DEC(HIDEREADONLY, OFN_HIDEREADONLY);
    DEC(NOCHANGEDIR, OFN_NOCHANGEDIR);
    DEC(ALLOWMULTISELECT, OFN_ALLOWMULTISELECT);
    DEC(PATHMUSTEXIST, OFN_PATHMUSTEXIST);
    DEC(FILEMUSTEXIST, OFN_FILEMUSTEXIST);
    DEC(NOREADONLYRETURN, OFN_NOREADONLYRETURN);
    printf("    }\n\n");

    printf("    // Registry\n");
    printf("    export const enum HKey {\n");
    DEC(CURRENT_USER, (LONG_PTR)HKEY_CURRENT_USER);
    DEC(LOCAL_MACHINE, (LONG_PTR)HKEY_LOCAL_MACHINE);
    printf("    }\n\n");

    printf("    export const enum RegAccess {\n");
    DEC(SET_VALUE, KEY_SET_VALUE);
    DEC(READ, KEY_READ);
    printf("    }\n\n");

    printf("    export const enum RegType {\n");
    DEC(SZ, REG_SZ);
    printf("    }\n\n");

    printf("    // Printer\n");
    printf("    export const enum PrinterEnum {\n");
    DEC(LOCAL, PRINTER_ENUM_LOCAL);
    DEC(CONNECTIONS, PRINTER_ENUM_CONNECTIONS);
    printf("    }\n\n");

    printf("    // DeviceCaps\n");
    printf("    export const enum DeviceCap {\n");
    DEC(HORZRES, HORZRES);
    DEC(VERTRES, VERTRES);
    DEC(LOGPIXELSX, LOGPIXELSX);
    DEC(LOGPIXELSY, LOGPIXELSY);
    printf("    }\n\n");

    printf("    // Static controls\n");
    printf("    export const enum StaticMsg {\n");
    DEC(SETICON, STM_SETICON);
    DEC(SETIMAGE, STM_SETIMAGE);
    DEC(GETICON, STM_GETICON);
    DEC(GETIMAGE, STM_GETIMAGE);
    printf("    }\n\n");

    printf("    export const enum StaticStyleEx {\n");
    DEC(LEFT, SS_LEFT);
    DEC(CENTER, SS_CENTER);
    DEC(RIGHT, SS_RIGHT);
    DEC(ICON, SS_ICON);
    DEC(BLACKRECT, SS_BLACKRECT);
    DEC(GRAYRECT, SS_GRAYRECT);
    DEC(WHITERECT, SS_WHITERECT);
    DEC(BLACKFRAME, SS_BLACKFRAME);
    DEC(GRAYFRAME, SS_GRAYFRAME);
    DEC(WHITEFRAME, SS_WHITEFRAME);
    DEC(SIMPLE, SS_SIMPLE);
    DEC(LEFTNOWORDWRAP, SS_LEFTNOWORDWRAP);
    DEC(OWNERDRAW, SS_OWNERDRAW);
    DEC(BITMAP, SS_BITMAP);
    DEC(ETCHEDHORZ, SS_ETCHEDHORZ);
    DEC(ETCHEDVERT, SS_ETCHEDVERT);
    DEC(ETCHEDFRAME, SS_ETCHEDFRAME);
    DEC(NOTIFY, SS_NOTIFY);
    DEC(CENTERIMAGE, SS_CENTERIMAGE);
    DEC(RIGHTJUST, SS_RIGHTJUST);
    DEC(SUNKEN, SS_SUNKEN);
    DEC(ENDELLIPSIS, SS_ENDELLIPSIS);
    DEC(PATHELLIPSIS, SS_PATHELLIPSIS);
    DEC(WORDELLIPSIS, SS_WORDELLIPSIS);
    DEC(REALSIZEIMAGE, SS_REALSIZEIMAGE);
    printf("    }\n\n");

    printf("    export const enum ImageType {\n");
    DEC(BITMAP, IMAGE_BITMAP);
    DEC(ICON, IMAGE_ICON);
    DEC(CURSOR, IMAGE_CURSOR);
    printf("    }\n\n");

    printf("    export const enum DrawTextFlag {\n");
    DEC(CALCRECT, DT_CALCRECT);
    printf("    }\n\n");

    printf("    // Process\n");
    printf("    export const enum ProcessCreationFlag {\n");
    DEC(NO_WINDOW, CREATE_NO_WINDOW);
    printf("    }\n\n");

    printf("    // Error codes\n");
    printf("    export const enum ErrorCode {\n");
    DEC(FILE_NOT_FOUND, ERROR_FILE_NOT_FOUND);
    DEC(PATH_NOT_FOUND, ERROR_PATH_NOT_FOUND);
    DEC(ACCESS_DENIED, ERROR_ACCESS_DENIED);
    DEC(INVALID_HANDLE, ERROR_INVALID_HANDLE);
    DEC(NOT_ENOUGH_MEMORY, ERROR_NOT_ENOUGH_MEMORY);
    DEC(OUTOFMEMORY, ERROR_OUTOFMEMORY);
    DEC(INVALID_PARAMETER, ERROR_INVALID_PARAMETER);
    DEC(ALREADY_EXISTS, ERROR_ALREADY_EXISTS);
    DEC(INSUFFICIENT_BUFFER, ERROR_INSUFFICIENT_BUFFER);
    DEC(MORE_DATA, ERROR_MORE_DATA);
    DEC(NO_DATA, ERROR_NO_DATA);
    printf("    }\n\n");

    printf("    // Power management\n");
    printf("    export const enum PowerBroadcast {\n");
    DEC(APMQUERYSUSPEND, PBT_APMQUERYSUSPEND);
    DEC(APMQUERYSTANDBY, PBT_APMQUERYSTANDBY);
    DEC(APMQUERYSUSPENDFAILED, PBT_APMQUERYSUSPENDFAILED);
    DEC(APMQUERYSTANDBYFAILED, PBT_APMQUERYSTANDBYFAILED);
    DEC(APMSUSPEND, PBT_APMSUSPEND);
    DEC(APMSTANDBY, PBT_APMSTANDBY);
    DEC(APMRESUMECRITICAL, PBT_APMRESUMECRITICAL);
    DEC(APMRESUMESUSPEND, PBT_APMRESUMESUSPEND);
    DEC(APMRESUMEAUTOMATIC, PBT_APMRESUMEAUTOMATIC);
    DEC(APMBATTERYLOW, PBT_APMBATTERYLOW);
    DEC(APMPOWERSTATUSCHANGE, PBT_APMPOWERSTATUSCHANGE);
    DEC(APMOEMEVENT, PBT_APMOEMEVENT);
    DEC(POWERSETTINGCHANGE, PBT_POWERSETTINGCHANGE);
    printf("    }\n\n");

    printf("    // DevMode\n");
    printf("    export const enum DevMode {\n");
    DEC(DUPLEX, DM_DUPLEX);
    DEC(OUT_BUFFER, DM_OUT_BUFFER);
    printf("    }\n\n");

    printf("    // COM GUIDs\n");
    printf("    export const enum Guid {\n");
    DEC_GUID("IID_ISHELLLINKW", IID_IShellLinkW);
    DEC_GUID("IID_IPERSISTFILE", IID_IPersistFile);
    printf("    }\n\n");

    printf("}\n\n");

    /* sock */
    printf("declare module \"sock\" {\n\n");

    printf("    export const enum AddrFamily {\n");
    DEC(AF_INET, AF_INET);
    printf("    }\n\n");

    printf("    export const enum SockType {\n");
    DEC(SOCK_STREAM, SOCK_STREAM);
    DEC(SOCK_DGRAM, SOCK_DGRAM);
    printf("    }\n\n");

    printf("    export const enum Protocol {\n");
    DEC(IPPROTO_TCP, IPPROTO_TCP);
    DEC(IPPROTO_UDP, IPPROTO_UDP);
    printf("    }\n\n");

    printf("    export const enum Shutdown {\n");
    DEC(SD_RECEIVE, SD_RECEIVE);
    DEC(SD_SEND, SD_SEND);
    DEC(SD_BOTH, SD_BOTH);
    printf("    }\n\n");

    printf("    export const enum FdEvent {\n");
    DEC(FD_READ, FD_READ);
    DEC(FD_WRITE, FD_WRITE);
    DEC(FD_CONNECT, FD_CONNECT);
    DEC(FD_CLOSE, FD_CLOSE);
    printf("    }\n\n");

    printf("}\n\n");

    /* wolfssl */
    printf("declare module \"wolfssl\" {\n\n");

    printf("    export const enum VerifyMode {\n");
    DEC(SSL_VERIFY_NONE, SSL_VERIFY_NONE);
    DEC(SSL_VERIFY_PEER, SSL_VERIFY_PEER);
    printf("    }\n\n");

    printf("    export const enum SniType {\n");
    DEC(WOLFSSL_SNI_HOST_NAME, WOLFSSL_SNI_HOST_NAME);
    printf("    }\n\n");

    printf("    export const enum FileType {\n");
    DEC(SSL_FILETYPE_PEM, SSL_FILETYPE_PEM);
    printf("    }\n\n");

    printf("    export const enum ReturnCode {\n");
    DEC(SSL_SUCCESS, SSL_SUCCESS);
    printf("    }\n\n");

    printf("    export const enum ErrorCode {\n");
    DEC(WOLFSSL_ERROR_WANT_READ, WOLFSSL_ERROR_WANT_READ);
    DEC(WOLFSSL_ERROR_WANT_WRITE, WOLFSSL_ERROR_WANT_WRITE);
    printf("    }\n\n");

    printf("}\n");
}

int main(void) {
    print_enums();
    return 0;
}
