#!/bin/sh
# 从 quickwin_const.d.ts 提取全部 const enum，生成 EnumMap 预填 quickwin_enum_map.d.ts。
# EnumMap 是 token 枚举标注（'u32@Name' / '<>ptr@Name'）的全局声明合并表（lib/ffi/ctype.ts），
# 用户可在自己的 .d.ts 里继续扩展。重名枚举（分属不同 declare module）取值域并集 ——
# token 不带模块前缀，作者标注时明知语义，收宽无害。
# 用法: tools/gen_enum_map.sh [src] [out]   （在仓库根执行；make gen-const 拷回 d.ts 后跑一次）
set -e
src=${1:-quickwin_const.d.ts}
out=${2:-quickwin_enum_map.d.ts}

awk '
    BEGIN { q = sprintf("%c", 39) }
    /^declare module "/ {
        mod = $3
        gsub(/"/, "", mod)
        next
    }
    /export const enum [A-Za-z0-9_]+/ {
        name = $4
        ref = "import(" q mod q ")." name
        if (name in seen) {
            # 同名第二次出现 → 追加为并集
            union[name] = union[name] " | " ref
            next
        }
        seen[name] = 1
        union[name] = ref
        order[++n] = name
    }
    END {
        print "// Auto-generated by tools/gen_enum_map.sh from quickwin_const.d.ts. DO NOT EDIT."
        print "// Regenerate with: make enum-map   (run after regenerating quickwin_const.d.ts)"
        print "//"
        print "// EnumMap — token 枚举标注 (\x27u32@Name\x27 / \x27<>ptr@Name\x27) 的值域表：全局"
        print "// interface 声明合并（详见 lib/ffi/ctype.ts），用户可在自己的 .d.ts 里直接扩展。"
        print "// 重名枚举取跨模块值域并集。"
        print "interface EnumMap {"
        for (i = 1; i <= n; i++) {
            k = order[i]
            printf("    %s: %s\n", k, union[k])
        }
        # 聚合消息枚举：msg 位（SendMessage/DefWindowProc）的值域是窗口消息 + 各控件消息
        # 的并集（WmMsg/TvMsg/LvMsg/...），单一枚举标不全 —— 按 *Msg 后缀自动聚合。
        any = ""
        for (i = 1; i <= n; i++) {
            k = order[i]
            if (k ~ /Msg$/)
                any = any (any == "" ? "" : " | ") union[k]
        }
        if (any != "") {
            print ""
            print "    // 聚合消息枚举（脚本按 *Msg 后缀自动收集）：SendMessage/DefWindowProc 的"
            print "    // msg 位值域 = 窗口消息 ∪ 各控件消息；标志位组合、通知码不在此域。"
            printf("    AnyMsg: %s\n", any)
        }
        print "}"
    }
' "$src" > "$out"

echo "wrote $out ($(grep -c '^    [A-Za-z]' "$out") entries)"
